### ISSUE TITLE
documentation: further work

### ISSUE THREAD

**Issue by classabbyamp** [zbm-dev/zfsbootmenu#380]
- [x] unify main website content and reference docs - #382 
- [ ] remove generate-zbm.8 from bin/generate-zbm (how should the help now be shown?)
- [x] migrate manpage releng stuff - #384 
- [x] migrate in-zbm online docs to rst2ansi (and rm /docs/pod/online) - #384 
- [ ] internal function documentation

**Comment by zdykstra** [comment]
- [ ] `releng/tag-release.sh` should also inform `docs/conf.py` about the version change in some fashion.
